const mongoose = require("mongoose");
const { getNextSequence } = require("../counters");

const settingsSchema = new mongoose.Schema(
  {
    id: { type: Number, required: false },
    hesabe_merchant_code: { type: String, required: true },
    hesabe_payment_mode: { type: Number, required: true },
    hesabe_payment_description: { type: String, required: true },
    hesabe_payment_description_arabic: { type: String, required: true },
    payment_description_arabic: { type: String, required: true },
    site_name: { type: String, required: true },
    site_name_french: { type: String, required: true },
    title_french: { type: String, required: true },
    meta_keywords: { type: String, required: true },
    meta_description: { type: String, required: true },
    title: { type: String, required: true },
    theme: { type: String, required: true },
    default_language: { type: String, required: true, default: "english" },
    contact_name: { type: String, required: true },
    contact_email: { type: String, required: true },
    webmaster_email: { type: String, required: true },
    noreply_email: { type: String, required: true },
    skype_id: { type: String, required: true },
    address1: { type: String, required: true },
    address2: { type: String, required: true },
    zipcode: { type: String, required: true },
    country: { type: Number, required: true },
    city: { type: Number, required: true },
    phone1: { type: String, required: true },
    phone2: { type: String, required: true },
    facebook_page: { type: String, required: true },
    instagram_page: { type: String, required: true },
    twitter_page: { type: String, required: true },
    linkedin_page: { type: String, required: true },
    android_page: { type: String, required: true },
    iphone_page: { type: String, required: true },
    facebook_fanpage: { type: String, required: true },
    youtube_url: { type: String, required: true },
    analytics_code: { type: String, required: true },
    facebook_app_id: { type: String, required: true },
    facebook_secret_key: { type: String, required: true },
    twitter_api_key: { type: String, required: true },
    twitter_secret_key: { type: String, required: true },
    gmap_api_key: { type: String, required: true },
    paypal_payment_mode: { type: Number, required: true },
    paypal_account_id: { type: String, required: true },
    paypal_api_password: { type: String, required: true },
    paypal_api_signature: { type: String, required: true },
    authorizenet_transaction_key: { type: String, required: true },
    authorizenet_api_id: { type: String, required: true },
    min_fund_request: { type: Number, required: true },
    max_fund_request: { type: Number, required: true },
    deal_commission: { type: Number, required: true },
    currency_symbol: { type: String, required: true },
    currency_code: { type: String, required: true },
    country_code: { type: String, required: true },
    referral_amount: { type: Number, required: true },
    site_mode: { type: Number, required: true, default: 1 },
    status: { type: Number, required: true, default: 1 },
    latitude: { type: String, required: true },
    longitude: { type: String, required: true },
    email_type: { type: Number, required: true, default: 1 },
    flat_shipping: { type: Number, required: true },
    tax_percentage: { type: Number, required: true },
    minimumProductQuantityToNotify: { type: Number, default: 5 },
    adminEmailAddress: { type: String },
    sendOutOfStockNotification: { type: Boolean, default: false },
    cancel_process: { type: Number, required: true },
    transaction_process: { type: Number, required: true },
    cancel_approved_by: { type: Number, required: true },
    return_days: { type: Number, required: true },
    return_type: { type: String, required: true },
    coupon_limit: { type: String, required: true },
    date_time_format: { type: String, required: true },
    expire_date: { type: String, required: true },
    create_date: { type: Number, required: true },
    expiry_date: { type: Number, required: true },
    time_zone: { type: String, required: true },
    domain_name: { type: String, required: true },
    merchant_count: { type: Number, required: true },
    package_type: { type: Number, required: true },
    profile_status: { type: Number, required: true },
    bill_payment_terms: { type: Number, required: true },
    website_language_settings: { type: Number, required: true },
    website_front_language_settings: { type: Number, required: true },
    ios_language_settings: { type: Number, required: true },
    ios_colorcode_settings: { type: Number, required: true },
    android_language_settings: { type: Number, required: true },
    android_colorcode_settings: { type: Number, required: true },
    pos_ios_language_settings: { type: Boolean, required: true },
    pos_ios_colorcode_settings: { type: Boolean, required: true },
    pos_android_language_settings: { type: Boolean, required: true },
    pos_android_colorcode_settings: { type: Boolean, required: true },
    seller_ios_language_settings: { type: Boolean, required: true },
    seller_ios_colorcode_settings: { type: Boolean, required: true },
    seller_android_language_settings: { type: Boolean, required: true },
    seller_android_colorcode_settings: { type: Boolean, required: true },
    online_store: { type: Boolean, required: true },
    mobile_app: { type: Boolean, required: true },
    pos: { type: Boolean, required: true },
    apps: { type: Boolean, required: true },
    buy_button: { type: Number, required: true },
    facebook: { type: Number, required: true },
    android_colorcode_time: { type: String, required: true },
    android_string_time: { type: String, required: true },
    ios_colorcode_time: { type: String, required: true },
    ios_string_time: { type: String, required: true },
    pos_ios_string_time: { type: String, required: true },
    pos_ios_colorcode_time: { type: String, required: true },
    pos_android_string_time: { type: String, required: true },
    pos_android_colorcode_time: { type: String, required: true },
    seller_ios_string_time: { type: String, required: true },
    seller_ios_colorcode_time: { type: String, required: true },
    seller_android_string_time: { type: String, required: true },
    seller_android_colorcode_time: { type: String, required: true },
    multiple_handler: { type: Number, required: true },
    express_delivery: { type: Number, required: true },
    express_delivery_days: { type: Number, required: true },
    express_delivery_terms: { type: String, required: true },
    normal_delivery: { type: Number, required: true },
    normal_delivery_days: { type: Number, required: true },
    normal_delivery_terms: { type: String, required: true },
    pickup_from_shop_amount: { type: Number, required: true },
    delivery_hours: { type: Number, required: true },
    pickup_from_shop_terms: { type: String, required: true },
    feature_product_limit: { type: Number, required: true },
    home_category_list: { type: Number, required: true },
    pagination_count: { type: Number, required: true },
    menu_listing_count: { type: Number, required: true },
    currency_digits: { type: Number, required: true, default: 3 },
    currency_pading: { type: String, required: true, default: "LEFT" },
    shop_days: { type: String, required: true },
    delivery_charge: { type: Number, required: true },
    mincart_amount: { type: Number, required: true, default: 0 },
    delivery_locations: { type: String },
  },
  {
    collection: "settings",
    timestamps: false,
  }
);

settingsSchema.pre("save", async function (next) {
  if (this.id == null) {
    this.id = await getNextSequence("settings");
  }
  next();
});

module.exports = mongoose.models.settings || mongoose.model("settings", settingsSchema);
