const mongoose = require("mongoose");
const { getNextSequence } = require("../counters");

const transactionSchema = new mongoose.Schema(
  {
    id: { type: Number, required: false },
    parent_id: { type: Number, required: true, default: 0 },
    cart_id: { type: Number, required: true },
    cart_item_id: { type: Number, required: true },
    user_id: { type: Number, required: true },
    product_id: { type: Number, required: true },
    payer_id: { type: String, required: true },
    payer_status: { type: String, required: true },
    country_code: { type: String, required: true },
    currency_code: { type: String, required: true },
    transaction_date: { type: Number, required: true },
    correlation_id: { type: String, required: true },
    acknowledgement: { type: String, required: true },
    firstname: { type: String, required: true },
    lastname: { type: String, required: true },
    transaction_id: { type: String, required: true },
    recipt_id: { type: String, required: true },
    transaction_type: { type: String, required: true },
    payment_type: { type: String, required: true },
    order_date: { type: Number, required: true },
    amount: { type: Number, required: true },
    referral_amount: { type: Number, required: true },
    shipping_amount: { type: Number, required: true },
    shipping_methods: { type: Number, required: true },
    tax_amount: { type: Number, required: true },
    payment_status: { type: String, required: true },
    pending_reason: { type: String, required: true },
    reason_code: { type: String, required: true },
    paypal_email: { type: String, required: true },
    quantity: { type: Number, required: true },
    type: { type: Number, required: true },
    captured: { type: Number, required: true },
    captured_transaction_id: { type: String, required: true },
    captured_date: { type: Number, required: true },
    captured_correlation_id: { type: String, required: true },
    captured_ack: { type: String, required: true },
    captured_payment_type: { type: String, required: true },
    captured_payment_status: { type: String, required: true },
    captured_pending_reason: { type: String, required: true },
    friend_gift_status: { type: Number, required: true, default: 0 },
    deal_merchant_commission: { type: Number, required: true },
    merchant_amount: { type: Number, required: true },
    coupon_mail_sent: { type: Number, required: true, default: 0 },
    product_size: { type: Number, required: true },
    product_color: { type: Number, required: true },
    aramex_currencycode: { type: String, required: true },
    merchantId: { type: String, required: true },
    email: { type: String, required: true },
    phone: { type: String, required: true },
    referenceNumber: { type: String, required: true },
    serviceKey: { type: String, required: true },
    itex_id: { type: String, required: true },
    used_coupon_code: { type: String, required: true },
    used_coupon_id: { type: Number, required: true },
    discount_amount: { type: Number, required: true },
    grand_total: { type: Number, required: true },
    cart_quantity: { type: Number, required: true },
    transfer_status: { type: Number, required: true },
    digital: { type: Number, required: true, default: 0 },
    coupon_apply: { type: Number, required: true, default: 0 },
    coupon_code: { type: String, required: true },
    coupon_amount: { type: String, required: true },
    coupon_percentage: { type: String, required: true, default: "" },
    wallet_apply: { type: Number, required: true, default: 0 },
    wallet_amount: { type: String, required: true, default: "" },
    package_number: { type: Number, required: true },
    shipping_information: { type: String, required: true },
    shipping_name: { type: String, required: true },
    shipping_address: { type: String, required: true },
    shipping_address1: { type: String, required: true },
    shipping_phone: { type: String, required: true },
    shipping_user_id: { type: Number, required: true },
    shipping_city: { type: String, required: true },
    shipping_state: { type: String, required: true },
    shipping_country: { type: String, required: true },
    zip: { type: String, required: true },
    tacking_id: { type: String, required: true },
    shipping_date: { type: Number, required: true },
    shipping_log: { type: String, required: true },
    delivery_status: { type: Number, required: true, default: 0 },
    admin_status: { type: Number, required: true, default: 0 },
  },
  {
    collection: "transaction",
    timestamps: false,
  }
);

transactionSchema.pre("save", async function (next) {
  if (this.id == null) {
    this.id = await getNextSequence("transaction");
  }
  next();
});

module.exports = mongoose.models.transaction || mongoose.model("transaction", transactionSchema);
