const { PUBLIC_IMAGE_FOLDER } = require("./constants");

const img = (file) => `${PUBLIC_IMAGE_FOLDER}${file}`;

const dummyProducts = [
  {
    deal_id: 9001,
    deal_title: "Wildflower Honey 500g",
    deal_title_french: "عسل الزهور البرية 500 جم",
    deal_key: "wildflower-honey-500g",
    deal_price: 65,
    deal_value: 49,
    having_size_color: 0,
    image: img("product-wildflower.png"),
    inStock: true,
    ratings: 4.5,
  },
  {
    deal_id: 9002,
    deal_title: "Sidr Honey 250g",
    deal_title_french: "عسل السدر 250 جم",
    deal_key: "sidr-honey-250g",
    deal_price: 95,
    deal_value: 79,
    having_size_color: 0,
    image: img("product-sidr.png"),
    inStock: true,
    ratings: 5,
  },
  {
    deal_id: 9003,
    deal_title: "Honey Gift Box",
    deal_title_french: "علبة هدايا العسل",
    deal_key: "honey-gift-box",
    deal_price: 149,
    deal_value: 119,
    having_size_color: 0,
    image: img("product-gift-box.png"),
    inStock: true,
    ratings: 4,
  },
  {
    deal_id: 9004,
    deal_title: "Acacia Honey 500g",
    deal_title_french: "عسل الأكاسيا 500 جم",
    deal_key: "acacia-honey-500g",
    deal_price: 70,
    deal_value: 55,
    having_size_color: 0,
    image: img("dummy-product-1.png"),
    inStock: true,
    ratings: 4.2,
  },
  {
    deal_id: 9005,
    deal_title: "Mountain Honey 350g",
    deal_title_french: "عسل الجبل 350 جم",
    deal_key: "mountain-honey-350g",
    deal_price: 85,
    deal_value: 69,
    having_size_color: 0,
    image: img("dummy-product-2.png"),
    inStock: true,
    ratings: 4.7,
  },
  {
    deal_id: 9006,
    deal_title: "Honey Sampler Trio",
    deal_title_french: "تشكيلة عسل ثلاثية",
    deal_key: "honey-sampler-trio",
    deal_price: 110,
    deal_value: 89,
    having_size_color: 0,
    image: img("dummy-product-3.png"),
    inStock: true,
    ratings: 4.3,
  },
];

exports.getDummyHomeData = () => ({
  bannerImages: [
    {
      banner_id: 1,
      image_title: "Fresh Honey Harvest",
      redirect_url: "/products",
      url: img("banner-1.png"),
    },
    {
      banner_id: 2,
      image_title: "From Our Apiaries",
      redirect_url: "/products",
      url: img("banner-2.png"),
    },
  ],
  categories: [
    {
      category_id: 1,
      category_name: "Raw Honey",
      category_name_french: "عسل خام",
      main_category_id: 0,
      sub_category_id: 0,
      category: [
        {
          category_id: 11,
          category_name: "Wildflower",
          category_name_french: "زهور برية",
          main_category_id: 1,
          sub_category_id: 1,
          category: [],
        },
        {
          category_id: 12,
          category_name: "Sidr",
          category_name_french: "سدر",
          main_category_id: 1,
          sub_category_id: 1,
          category: [],
        },
      ],
    },
    {
      category_id: 2,
      category_name: "Gift Sets",
      category_name_french: "هدايا",
      main_category_id: 0,
      sub_category_id: 0,
      category: [
        {
          category_id: 21,
          category_name: "Premium Boxes",
          category_name_french: "علب فاخرة",
          main_category_id: 2,
          sub_category_id: 2,
          category: [],
        },
      ],
    },
    {
      category_id: 3,
      category_name: "Comb Honey",
      category_name_french: "عسل بالشمع",
      main_category_id: 0,
      sub_category_id: 0,
      category: [],
    },
  ],
  newProducts: dummyProducts.slice(0, 4),
  bestSellingProducts: [
    dummyProducts[1],
    dummyProducts[0],
    dummyProducts[2],
    dummyProducts[4],
  ],
  offerProducts: [
    dummyProducts[2],
    dummyProducts[5],
    dummyProducts[0],
    dummyProducts[3],
  ],
});

exports.getDummySiteSettingsExtras = () => ({
  offer_poster: img("poster.png"),
  login_page_image: img("login-image.png"),
  signin_page_image: img("login-image.png"),
  footer_logo: img("footer-logo.svg"),
  offer_text: "UP TO 30 % OFF",
  site_name: "Al-Thunayan Honey",
  title: "Al-Thunayan Honey Shop",
  contact_email: "hello@althunayanhoney.demo",
  phone1: "+971 55 000 0000",
  address1: "Muwaileh Commercial",
  address2: "Sharjah, UAE",
  zipcode: "00000",
  currency_symbol: "AED",
  currency_code: "AED",
});
